# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdProductoOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_online', models.CharField(help_text='algun identificador unico del producto en el sitio online. Ejemplo el PLU de Cotodigital', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Url al detalle del producto en la sucursal, si existe', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.Sucursal')),
            ],
        ),
    ]
