# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:22
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]