# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cadenas', models.ManyToManyField(blank=True, null=True, to='precios.Cadena')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioEnAcuerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_en_acuerdo', to='acuerdos.Acuerdo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudades', models.ManyToManyField(editable=False, related_name='region_en_acuerdo', to='cities_light.City')),
                ('ciudades_excluidas', models.ManyToManyField(related_name='excluida_de_region_acuerdo', to='cities_light.City')),
                ('ciudades_incluidas', models.ManyToManyField(related_name='incluida_en_region_acuerdo', to='cities_light.City')),
                ('provincias', models.ManyToManyField(related_name='incluida_en_region_acuerdo', to='cities_light.Region')),
            ],
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuerdos.Region'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='sucursales',
            field=models.ManyToManyField(blank=True, null=True, to='precios.Sucursal'),
        ),
    ]
