# -*- coding: utf-8 -*-
"""
script para el ticket #200
basado en estos resultados de votacion de voluntarios

https://github.com/mgaitan/preciosa/issues/200#issuecomment-37727675

mas una edicion a mano.

    [((937, None), 'cant 20', u'A CLASIFICAR > Aceites', ''),
     ((904, 234),
      'cant 44',
      u'A CLASIFICAR > Aceitunas',
      u'Almacen > Aceitunas y encurtidos > Aceitunas verdes'),
     ((885, 261),
      'cant 14',
      u'A CLASIFICAR > Aceto Bals\xe1mico y Vinagre',
      u'Almacen > Condimentos > Vinagre'),
     ((888, 661),
      'cant 48',
      u'A CLASIFICAR > Acondicionador',
      u'Perfumeria > Cuidado del cabello > Acondicionador'),
     ((872, 260),
      'cant 58',
      u'A CLASIFICAR > Aderezos',
      u'Almacen > Condimentos > Salsas'),
     ((852, 651),
      'cant 24',
      u'A CLASIFICAR > Afeitado',
      u'Perfumeria > Afeitado > Cremas/ espumas'),
     ((906, 378),
      'cant 41',
      u'A CLASIFICAR > Aguas',
      u'Bebidas sin alcohol > Aguas > Saborizadas'),
     ((809, 378),
      'cant 28',
      u'A CLASIFICAR > Aguas Saborizadas',
      u'Bebidas sin alcohol > Aguas > Saborizadas'),
     ((820, 445),
      'cant 11',
      u'A CLASIFICAR > Ahumados',
      u'Fiambreria > Fiambres > Ahumados'),
     ((803, 654),
      'cant 6',
      u'A CLASIFICAR > Algod\xf3n',
      u'Perfumeria > Algodon/ hisopos > Algodon/ hisopos'),
     ((839, 351),
      'cant 35',
      u'A CLASIFICAR > Aperitivos',
      u'Bebidas con alcohol > Aperitivos > Vermouth'),
     ((849, None), 'cant 21', u'A CLASIFICAR > Arroz', ''),
     ((895, 243),
      'cant 38',
      u'A CLASIFICAR > Az\xfacar y Endulzantes',
      u'Almacen > Azucar y edulcorante > Edulcorante'),
     ((943, 333),
      'cant 32',
      u'A CLASIFICAR > Bazar',
      u'Bazar > Cristaleria > Vasos'),
     ((864, 352),
      'cant 18',
      u'A CLASIFICAR > Bebidas Blancas',
      u'Bebidas con alcohol > Blancas > Blancas'),
     ((797, 380),
      'cant 4',
      u'A CLASIFICAR > Bebidas Energizantes',
      u'Bebidas sin alcohol > Energizantes > Energizantes'),
     ((784, 360),
      'cant 4',
      u'A CLASIFICAR > Bebidas Fizz',
      u'Bebidas con alcohol > Sidras- otros > Sidras- otros'),
     ((918, 388),
      'cant 13',
      u'A CLASIFICAR > Bebidas Isot\xf3nicas',
      u'Bebidas sin alcohol > Isotonicas > Isotonicas'),
     ((846, 464),
      'cant 9',
      u'A CLASIFICAR > Bizcochos',
      u'Golosinas y galletitas > Bizcochos > Bizcochos'),
     ((801, 413),
      'cant 10',
      u'A CLASIFICAR > Bocaditos',
      u'Congelados > Rebozados > Pollo'),
     ((893, 575),
      'cant 13',
      u'A CLASIFICAR > Bolsas para Residuos',
      u'Limpieza > Cocina > Descartables'),
     ((911, 290),
      'cant 14',
      u'A CLASIFICAR > Brownies y Budines',
      u'Almacen > Panificados > Budines/otros'),
     ((919, 278),
      'cant 5',
      u'A CLASIFICAR > Cacao en Polvo',
      u'Almacen > Infusiones > Cacao'),
     ((934, 279),
      'cant 48',
      u'A CLASIFICAR > Caf\xe9',
      u'Almacen > Infusiones > Cafe instantaneo'),
     ((877, 314),
      'cant 16',
      u'A CLASIFICAR > Caldos y Saborizadores',
      u'Almacen > Sopas y caldos > Saborizadores'),
     ((914, 676),
      'cant 27',
      u'A CLASIFICAR > Cepillos Dentales',
      u'Perfumeria > Cuidado oral > Cepillos'),
     ((881, 248),
      'cant 49',
      u'A CLASIFICAR > Cereales',
      u'Almacen > Cereales > Frutal'),
     ((931, 354),
      'cant 29',
      u'A CLASIFICAR > Cervezas',
      u'Bebidas con alcohol > Cervezas > Botella'),
     ((836, 478),
      'cant 15',
      u'A CLASIFICAR > Chocolates',
      u'Golosinas y galletitas > Golosinas > Chocolates y tablet'),
     ((857, 306),
      'cant 5',
      u'A CLASIFICAR > Coberturas',
      u'Almacen > Reposteria > Reposteria'),
     ((899, 576),
      'cant 42',
      u'A CLASIFICAR > Cocina',
      u'Limpieza > Cocina > Detergente- lavavajilla'),
     ((927, 629),
      'cant 7',
      u'A CLASIFICAR > Colonia para Beb\xe9s',
      u'Mamas y bebes > Fragancias > Bebes/ ni\xf1os'),
     ((869, 690),
      'cant 10',
      u'A CLASIFICAR > Colonias y Perfumes',
      u'Perfumeria > Farmacia > Venta libre'),
     ((868, 643),
      'cant 3',
      u'A CLASIFICAR > Comidas Preparadas',
      u'Panaderia > Otros > Varios'),
     ((855, 626),
      'cant 10',
      u'A CLASIFICAR > Comidas para Beb\xe9s',
      u'Mamas y bebes > Alimentacion infantil > Papilla'),
     ((945, 253),
      'cant 38',
      u'A CLASIFICAR > Condimentos y Especias',
      u'Almacen > Condimentos > Especias'),
     ((898, None), 'cant 28', u'A CLASIFICAR > Conservas', ''),
     ((860, 501),
      'cant 4',
      u'A CLASIFICAR > Cremas',
      u'Lacteos > Cremas > Cremas'),
     ((775, 657),
      'cant 38',
      u'A CLASIFICAR > Cremas Corporales',
      u'Perfumeria > Cuidado de la piel > Cremas'),
     ((798, 677),
      'cant 40',
      u'A CLASIFICAR > Cremas Dentales',
      u'Perfumeria > Cuidado oral > Cremas'),
     ((861, 672),
      'cant 17',
      u'A CLASIFICAR > Cremas Faciales',
      u'Perfumeria > Cuidado facial > Hidratacion'),
     ((816, 657),
      'cant 17',
      u'A CLASIFICAR > Cuidado de la Piel',
      u'Perfumeria > Cuidado de la piel > Cremas'),
     ((782, 661),
      'cant 28',
      u'A CLASIFICAR > Cuidado del Cabello',
      u'Perfumeria > Cuidado del cabello > Acondicionador'),
     ((796, 658),
      'cant 11',
      u'A CLASIFICAR > Depilaci\xf3n',
      u'Perfumeria > Cuidado de la piel > Depilacion'),
     ((805, 682),
      'cant 27',
      u'A CLASIFICAR > Desodorantes',
      u'Perfumeria > Desodorantes > Mujer'),
     ((831, 584),
      'cant 30',
      u'A CLASIFICAR > Desodorantes de Ambientes',
      u'Limpieza > Desodorante de ambiente > Aerosoles'),
     ((858, 622),
      'cant 2',
      u'A CLASIFICAR > Destapaca\xf1er\xedas',
      u'Limpieza > Varios > Varios'),
     ((887, 270),
      'cant 24',
      u'A CLASIFICAR > Dulces',
      u'Almacen > Dulces > Mermelada'),
     ((824, 630),
      'cant 9',
      u'A CLASIFICAR > Emulsiones Limpiadoras para Beb\xe9s',
      u'Mamas y bebes > Oleo calcareo > Oleo calcareo'),
     ((891, 678),
      'cant 17',
      u'A CLASIFICAR > Enjuagues Bucales',
      u'Perfumeria > Cuidado oral > Enjuagues'),
     ((793, 589),
      'cant 13',
      u'A CLASIFICAR > Escobas, Escobillones y Cepillos',
      u'Limpieza > Escobas y cabos > Escobas- cepillos'),
     ((938, 591),
      'cant 9',
      u'A CLASIFICAR > Esponjas',
      u'Limpieza > Esponjas > Esponjas'),
     ((896, None), 'cant 17', u'A CLASIFICAR > Farmacia', ''),
     ((933, 449),
      'cant 26',
      u'A CLASIFICAR > Fiambres y Embutidos',
      u'Fiambreria > Fiambres > Mortadela/ salchichon'),
     ((804, 459),
      'cant 2',
      u'A CLASIFICAR > Frutas',
      u'Frutas y verduras > Frutas > Frutas'),
     ((915, None), 'cant 38', u'A CLASIFICAR > Galletas y Galletitas', ''),
     ((818, 384),
      'cant 25',
      u'A CLASIFICAR > Gaseosas',
      u'Bebidas sin alcohol > Gaseosas > Otras'),
     ((874, 697),
      'cant 2',
      u'A CLASIFICAR > Gel de Ducha',
      u'Perfumeria > Jabones > Liquidos'),
     ((892, 472),
      'cant 0',
      u'A CLASIFICAR > Grisines',
      u'Golosinas y galletitas > Galletitas saladas > Grisines- marineras'),
     ((875, None), 'cant 15', u'A CLASIFICAR > Guantes Multiuso', ''),
     ((835, 406),
      'cant 19',
      u'A CLASIFICAR > Hamburguesas',
      u'Congelados > Hamburguesas > Carne'),
     ((834, 274),
      'cant 18',
      u'A CLASIFICAR > Harinas',
      u'Almacen > Harinas > Premezcla'),
     ((912, None), 'cant 12', u'A CLASIFICAR > Helados y Postres', ''),
     ((940, 679),
      'cant 1',
      u'A CLASIFICAR > Hilo Dental',
      u'Perfumeria > Cuidado oral > Hilo'),
     ((871, 654),
      'cant 7',
      u'A CLASIFICAR > Hisopos',
      u'Perfumeria > Algodon/ hisopos > Algodon/ hisopos'),
     ((806, 277),
      'cant 9',
      u'A CLASIFICAR > Huevos',
      u'Almacen > Huevos > Huevos'),
     ((883, None), 'cant 18', u'A CLASIFICAR > Infusiones', ''),
     ((913, 593),
      'cant 15',
      u'A CLASIFICAR > Insecticidas y Repelentes',
      u'Limpieza > Insecticidas > Cucarachas'),
     ((842, 697),
      'cant 4',
      u'A CLASIFICAR > Jabones y Ba\xf1os L\xedquidos',
      u'Perfumeria > Jabones > Liquidos'),
     ((917, 665),
      'cant 17',
      u'A CLASIFICAR > Jabones y Ba\xf1os L\xedquidos para Beb\xe9s',
      u'Perfumeria > Cuidado del cabello > Infantil'),
     ((813, 391),
      'cant 32',
      u'A CLASIFICAR > Jugos',
      u'Bebidas sin alcohol > Jugos > Listos'),
     ((902, 390),
      'cant 65',
      u'A CLASIFICAR > Jugos en Polvo',
      u'Bebidas sin alcohol > Jugos > En polvo'),
     ((790, 600),
      'cant 16',
      u'A CLASIFICAR > Lavandinas',
      u'Limpieza > Limpiadores > Pisos'),
     ((882, 506),
      'cant 15',
      u'A CLASIFICAR > Leche',
      u'Lacteos > Leche > Descremada'),
     ((788, 287),
      'cant 5',
      u'A CLASIFICAR > Leche en Polvo',
      u'Almacen > Leche en polvo > Entera'),
     ((795, 625),
      'cant 22',
      u'A CLASIFICAR > Leche y F\xf3rmulas para Beb\xe9s',
      u'Mamas y bebes > Alimentacion infantil > Leche - alimento'),
     ((910, 511),
      'cant 1',
      u'A CLASIFICAR > Levaduras',
      u'Lacteos > Levaduras y grasas > Levaduras y grasas'),
     ((812, 550),
      'cant 2',
      u'A CLASIFICAR > Librer\xeda y Oficinas',
      u'Libreria > Oficina > Cintas/ dispensores'),
     ((878, 359),
      'cant 33',
      u'A CLASIFICAR > Licores',
      u'Bebidas con alcohol > Licores > Licores'),
     ((890, 579),
      'cant 17',
      u'A CLASIFICAR > Limpiador de Vidrios y Multiusos',
      u'Limpieza > Cocina > Limpiadores- desengrasantes'),
     ((832, 657),
      'cant 10',
      u'A CLASIFICAR > Limpieza Facial',
      u'Perfumeria > Cuidado de la piel > Cremas'),
     ((942, None), 'cant 31', u'A CLASIFICAR > Limpieza de Pisos', ''),
     ((862, 575),
      'cant 50',
      u'A CLASIFICAR > Limpieza de la Cocina',
      u'Limpieza > Cocina > Descartables'),
     ((845, 621),
      'cant 17',
      u'A CLASIFICAR > Limpieza de la Ropa',
      u'Limpieza > Ropa > Suavizante'),
     ((776, 598),
      'cant 45',
      u'A CLASIFICAR > Limpieza del Ba\xf1o',
      u'Limpieza > Limpiadores > Ba\xf1o'),
     ((897, 572),
      'cant 9',
      u'A CLASIFICAR > Limpieza del Calzado',
      u'Limpieza > Calzado > Pomada'),
     ((924, 599),
      'cant 17',
      u'A CLASIFICAR > Limpieza del Hogar',
      u'Limpieza > Limpiadores > Cocina'),
     ((946, None), 'cant 1', u'A CLASIFICAR > Loci\xf3n Antimosquito', ''),
     ((819, 622),
      'cant 0',
      u'A CLASIFICAR > Lustra Metales',
      u'Limpieza > Varios > Varios'),
     ((922, 610),
      'cant 7',
      u'A CLASIFICAR > Lustra Muebles',
      u'Limpieza > Pisos > Limpiadores'),
     ((799, 434),
      'cant 3',
      u'A CLASIFICAR > L\xe1mparas',
      u'Ferreteria > Lamparitas > Lamparitas'),
     ((823, None), 'cant 0', u'A CLASIFICAR > Maltas', ''),
     ((791, 702),
      'cant 5',
      u'A CLASIFICAR > Manos y U\xf1as',
      u'Perfumeria > Manos y pies > Quitaesmalte'),
     ((777, None), 'cant 11', u'A CLASIFICAR > Mantecas y Margarinas', ''),
     ((856, None), 'cant 0', u'A CLASIFICAR > Maquillaje', ''),
     ((865, None), 'cant 5', u'A CLASIFICAR > Mascotas', ''),
     ((778, 282),
      'cant 4',
      u'A CLASIFICAR > Mate Cocido',
      u'Almacen > Infusiones > Mate cocido'),
     ((785, 413),
      'cant 4',
      u'A CLASIFICAR > Medallones de Pollo',
      u'Congelados > Rebozados > Pollo'),
     ((932, 414),
      'cant 10',
      u'A CLASIFICAR > Milanesas de Soja',
      u'Congelados > Rebozados > Soja'),
     ((923, 374),
      'cant 10',
      u'A CLASIFICAR > Otras Bebidas con Alcohol',
      u'Bebidas con alcohol > Vino tinto > Otras cepas'),
     ((783, 387),
      'cant 3',
      u'A CLASIFICAR > Otras Bebidas sin Alcohol',
      u'Bebidas sin alcohol > Hierbas > Hierbas'),
     ((939, 412),
      'cant 10',
      u'A CLASIFICAR > Otros Alimentos Congelados',
      u'Congelados > Rebozados > Pescado'),
     ((901, 601),
      'cant 10',
      u'A CLASIFICAR > Otros Limpiadores Desinfectantes',
      u'Limpieza > Limpiadores > Placard- muebles'),
     ((773, 643),
      'cant 2',
      u'A CLASIFICAR > Otros Panes',
      u'Panaderia > Otros > Varios'),
     ((780, 226),
      'cant 0',
      u'A CLASIFICAR > Otros Productos Frescos',
      u'Almacen > Aceites > Aerosol'),
     ((781, 628),
      'cant 1',
      u'A CLASIFICAR > Otros Productos de Limpieza',
      u'Mamas y bebes > Cuidado mama > Cuidado mama'),
     ((807, 627),
      'cant 7',
      u'A CLASIFICAR > Otros Productos para Beb\xe9s',
      u'Mamas y bebes > Chupetes/ mamaderas > Chupetes/ mamaderas'),
     ((920, 642),
      'cant 3',
      u'A CLASIFICAR > Otros Productos para el Hogar',
      u'Mascotas > Alimento perro > Cachorro'),
     ((909, 290),
      'cant 0',
      u'A CLASIFICAR > Pan Dulce',
      u'Almacen > Panificados > Budines/otros'),
     ((867, 292),
      'cant 1',
      u'A CLASIFICAR > Pan Integral',
      u'Almacen > Panificados > Pan de molde'),
     ((837, 292),
      'cant 0',
      u'A CLASIFICAR > Pan Lacteado',
      u'Almacen > Panificados > Pan de molde'),
     ((889, 292),
      'cant 2',
      u'A CLASIFICAR > Pan de Cereal',
      u'Almacen > Panificados > Pan de molde'),
     ((907, 644),
      'cant 0',
      u'A CLASIFICAR > Pan de Mesa',
      u'Panaderia > Pan > Elaboracion propia'),
     ((794, 292),
      'cant 0',
      u'A CLASIFICAR > Pan de Salvado',
      u'Almacen > Panificados > Pan de molde'),
     ((854, 291),
      'cant 0',
      u'A CLASIFICAR > Pan para Hamburguesas',
      u'Almacen > Panificados > Hamb/ panchos'),
     ((840, 291),
      'cant 0',
      u'A CLASIFICAR > Pan para Panchos',
      u'Almacen > Panificados > Hamb/ panchos'),
     ((838, 289),
      'cant 2',
      u'A CLASIFICAR > Pan \xc1rabe',
      u'Almacen > Panificados > Arabe'),
     ((851, 643),
      'cant 12',
      u'A CLASIFICAR > Panificados',
      u'Panaderia > Otros > Varios'),
     ((930, 411),
      'cant 12',
      u'A CLASIFICAR > Papas Fritas',
      u'Congelados > Papas fritas > Papas fritas'),
     ((894, 607),
      'cant 3',
      u'A CLASIFICAR > Papeles Higi\xe9nicos',
      u'Limpieza > Papeles > Papel higienico'),
     ((863, 298),
      'cant 8',
      u'A CLASIFICAR > Pastas',
      u'Almacen > Pastas > Rellenas- otras'),
     ((941, 647),
      'cant 27',
      u'A CLASIFICAR > Pastas Frescas',
      u'Pastas y tapas > Pastas > Rellenas'),
     ((841, 296),
      'cant 36',
      u'A CLASIFICAR > Pastas Secas',
      u'Almacen > Pastas > Integrales- otros'),
     ((944, None), 'cant 16', u'A CLASIFICAR > Pa\xf1ales Descartables', ''),
     ((789, 637),
      'cant 1',
      u'A CLASIFICAR > Pa\xf1ales para Adultos',
      u'Mamas y bebes > Varios > Accesorios'),
     ((792, 612),
      'cant 11',
      u'A CLASIFICAR > Pa\xf1os Multiuso y Trapos de Piso',
      u'Limpieza > Pisos > Trapos- mopas'),
     ((879, 606),
      'cant 2',
      u'A CLASIFICAR > Pa\xf1uelos Descartables',
      u'Limpieza > Papeles > Pa\xf1uelos'),
     ((866, 428),
      'cant 5',
      u'A CLASIFICAR > Pegamentos',
      u'Ferreteria > Adhesivos > Adhesivos'),
     ((870, 435),
      'cant 0',
      u'A CLASIFICAR > Pilas',
      u'Ferreteria > Pilas > Pilas'),
     ((884, 292),
      'cant 2',
      u'A CLASIFICAR > Pionono',
      u'Almacen > Panificados > Pan de molde'),
     ((808, 405),
      'cant 8',
      u'A CLASIFICAR > Pizzas',
      u'Congelados > Comidas > Pizzas'),
     ((828, 613),
      'cant 1',
      u'A CLASIFICAR > Plumeros',
      u'Limpieza > Plumeros- limpiavidrios > Plumeros- limpiavidrios'),
     ((926, 635),
      'cant 8',
      u'A CLASIFICAR > Polvo de F\xe9cula y Talco para Beb\xe9s',
      u'Mamas y bebes > Talco/ fecula > Talco/ fecula'),
     ((817, 303),
      'cant 6',
      u'A CLASIFICAR > Polvos Instant\xe1neos',
      u'Almacen > Postres > Postres'),
     ((811, 303),
      'cant 44',
      u'A CLASIFICAR > Postres Fr\xedos',
      u'Almacen > Postres > Postres'),
     ((848, 303),
      'cant 1',
      u'A CLASIFICAR > Postres Instant\xe1neos',
      u'Almacen > Postres > Postres'),
     ((903, 643),
      'cant 1',
      u'A CLASIFICAR > Prepizzas',
      u'Panaderia > Otros > Varios'),
     ((786, 688),
      'cant 15',
      u'A CLASIFICAR > Preservativos',
      u'Perfumeria > Farmacia > Preservativos'),
     ((779, 706),
      'cant 23',
      u'A CLASIFICAR > Protecci\xf3n Femenina',
      u'Perfumeria > Proteccion femenina > Toallitas'),
     ((774, 297),
      'cant 4',
      u'A CLASIFICAR > Protectores Mamarios',
      u'Almacen > Pastas > Largos'),
     ((844, 675),
      'cant 3',
      u'A CLASIFICAR > Pr\xf3tesis Dentales',
      u'Perfumeria > Cuidado oral > Adhesivos'),
     ((925, 304),
      'cant 3',
      u'A CLASIFICAR > Pur\xe9 Instant\xe1neos',
      u'Almacen > Pure instantaneo > Pure instantaneo'),
     ((825, None), 'cant 21', u'A CLASIFICAR > Quesos', ''),
     ((929, 457),
      'cant 16',
      u'A CLASIFICAR > Quesos Rallados',
      u'Fiambreria > Quesos > Rallados'),
     ((876, 456),
      'cant 30',
      u'A CLASIFICAR > Quesos Untables',
      u'Fiambreria > Quesos > Quesos untables'),
     ((880, 293),
      'cant 2',
      u'A CLASIFICAR > Rebozadores',
      u'Almacen > Panificados > Pan rallado'),
     ((847, 469),
      'cant 11',
      u'A CLASIFICAR > Reposter\xeda y Golosinas',
      u'Golosinas y galletitas > Galletitas dulces > Rellenas'),
     ((936, 444),
      'cant 9',
      u'A CLASIFICAR > Salchichas',
      u'Fiambreria > Embutidos > Salchichas'),
     ((830, 316),
      'cant 36',
      u'A CLASIFICAR > Salsas',
      u'Almacen > Tomates y salsas > Salsas'),
     ((822, 266),
      'cant 2',
      u'A CLASIFICAR > Salteados',
      u'Almacen > Conservas > Vegetales'),
     ((800, 634),
      'cant 5',
      u'A CLASIFICAR > Seguridad para el Beb\xe9',
      u'Mamas y bebes > Seguridad > Seguridad'),
     ((826, 666),
      'cant 55',
      u'A CLASIFICAR > Shampoo',
      u'Perfumeria > Cuidado del cabello > Shampoo'),
     ((802, 360),
      'cant 3',
      u'A CLASIFICAR > Sidras',
      u'Bebidas con alcohol > Sidras- otros > Sidras- otros'),
     ((886, 308),
      'cant 54',
      u'A CLASIFICAR > Snacks',
      u'Almacen > Snacks > Frutas secas'),
     ((916, 315),
      'cant 40',
      u'A CLASIFICAR > Sopas',
      u'Almacen > Sopas y caldos > Sopas'),
     ((787, 650),
      'cant 25',
      u'A CLASIFICAR > Tapas',
      u'Pastas y tapas > Tapas > Tartas'),
     ((900, 404),
      'cant 5',
      u'A CLASIFICAR > Tartas',
      u'Congelados > Comidas > Otros'),
     ((921, 636),
      'cant 18',
      u'A CLASIFICAR > Toallitas H\xfamedas',
      u'Mamas y bebes > Toallitas humedas > Toallitas humedas'),
     ((850, 294),
      'cant 13',
      u'A CLASIFICAR > Tostadas',
      u'Almacen > Panificados > Tostadas'),
     ((905, 283),
      'cant 63',
      u'A CLASIFICAR > T\xe9',
      u'Almacen > Infusiones > Te'),
     ((821, 637),
      'cant 3',
      u'A CLASIFICAR > Vajilla para Beb\xe9s',
      u'Mamas y bebes > Varios > Accesorios'),
     ((827, 416),
      'cant 8',
      u'A CLASIFICAR > Vegetales',
      u'Congelados > Vegetales > Vegetales'),
     ((833, 582),
      'cant 5',
      u'A CLASIFICAR > Velas & Aromatizadores',
      u'Limpieza > Cocina > Velas'),
     ((829, 362),
      'cant 60',
      u'A CLASIFICAR > Vinos Blancos',
      u'Bebidas con alcohol > Vino blanco > Otras cepas'),
     ((935, 356),
      'cant 44',
      u'A CLASIFICAR > Vinos Espumantes',
      u'Bebidas con alcohol > Espumantes > Champagne'),
     ((908, 357),
      'cant 8',
      u'A CLASIFICAR > Vinos Gasificados',
      u'Bebidas con alcohol > Espumantes > Frizantes'),
     ((928, 374),
      'cant 5',
      u'A CLASIFICAR > Vinos Rosados',
      u'Bebidas con alcohol > Vino tinto > Otras cepas'),
     ((873, 374),
      'cant 62',
      u'A CLASIFICAR > Vinos Tintos',
      u'Bebidas con alcohol > Vino tinto > Otras cepas'),
     ((810, 352),
      'cant 4',
      u'A CLASIFICAR > Whiskys',
      u'Bebidas con alcohol > Blancas > Blancas'),
     ((815, 284),
      'cant 21',
      u'A CLASIFICAR > Yerba Mate',
      u'Almacen > Infusiones > Yerba'),
     ((853, 521),
      'cant 23',
      u'A CLASIFICAR > Yogurts',
      u'Lacteos > Yogur descremado > Bebible')]
"""
from django.db import transaction
from preciosa.precios.models import Categoria


def _generar_codigo_de_destinos_para(cat_depth2):
    """un helper para generar codigos de destino"""
    line = "%s = Categoria.objects.get(id=%d)"
    for cat in cat_depth2.get_children():

        print line % (cat.busqueda.split()[-1], cat.id)


def mover(origen, intento_borrar=False, log=True, **kwargs):
    """
    mueve los productos de la categoria origen
    a las de destino, basadas en la kwarg keyword sobre el campo busqueda

    Ejemplo ::

        >>> # origen
            aceitunas = Categoria.objects.get(id=904)

            # destinos
            negras = Categoria.objects.get(id=232)
            verdes = Categoria.objects.get(id=234)
            mover(aceitunas, negras=negras, verdes=verdes)

    Moverá todas los productos de ``aceitunas`` a ``verdes``
    las que tengan en su descripcion (campo ``busqueda``) la palabra
    clave ``verdes`` y a ``negras``  las que tengan la palabra clave
    ``negras``.

    Si ``intento_borrar`` es True, se elimina la categoria origen
    cuando no quedan productos.

    Si ``log`` es True imprime el movimiento
    """
    try:
        with transaction.atomic():
            for tipo, destino in kwargs.items():
                for p in origen.productos.filter(busqueda__icontains=tipo):
                    p.categoria = destino
                    p.save(update_fields=['categoria'])
                    if log:
                        print p, "=>", destino

            if intento_borrar and origen.productos.count() == 0:
                print u"%s quedó vacia y se eliminará" % origen
                origen.delete()
    except Exception as e:
        print u"Hubo un error **no se migró nada**"
        print e.message


def aceites():
    # categoria origen
    aceites = Categoria.objects.get(id=937)

    # destinos
    girasol = Categoria.objects.get(id=228)
    oliva = Categoria.objects.get(id=231)
    maiz = Categoria.objects.get(id=229)

    mover(aceites, intento_borrar=True,
          girasol=girasol, oliva=oliva, maiz=maiz)


def aceitunas():
    # origen
    aceitunas = Categoria.objects.get(id=904)

    # destinos
    negra = Categoria.objects.get(id=232)
    verde = Categoria.objects.get(id=234)
    rellena = Categoria.objects.get(id=233)
    encurtido = Categoria.objects.get(id=235)

    mover(aceitunas, intento_borrar=True,
          rellena=rellena, negra=negra, verde=verde,
          encurtido=encurtido)

    # mover
    # <Categoria: Fiambreria > Aceitunas/ encurtidos > Aceitunas/ encurtidos>
    aceituna_en_fiambreria = Categoria.objects.get(id=440)
    mover(aceituna_en_fiambreria, escabeche=encurtido)
    aceituna_en_fiambreria.get_parent().delete()


def vinagre_aceto():
    # origen
    origen = Categoria.objects.get(id=885)

    # destinos
    aceto = Categoria.objects.get(id=252)
    vinagre = Categoria.objects.get(id=261)

    mover(origen, intento_borrar=True,
          aceto=aceto, vinagre=vinagre)
