# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import image_cropping.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=b'empresas')),
                ('logo_cropped', image_cropping.fields.ImageRatioField(b'logo', '150x125', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recortar logo')),
                ('logo_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor=b'logo')),
                ('cadena_madre', models.ForeignKey(blank=True, help_text=b'Ej: Jumbo y Vea son de Cencosud', null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.Cadena')),
            ],
            options={
                'verbose_name': 'cadena de supermercados',
                'verbose_name_plural': 'cadenas de supermercados',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('oculta', models.BooleanField(default=False)),
                ('busqueda', models.CharField(editable=False, max_length=300)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='DescripcionAlternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, unique=True)),
                ('busqueda', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaFabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=b'empresas')),
                ('logo_cropped', image_cropping.fields.ImageRatioField(b'logo', '150x125', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recortar logo')),
                ('logo_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor=b'logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la marca')),
                ('logo', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=b'marcas')),
                ('logo_cropped', image_cropping.fields.ImageRatioField(b'logo', '150x125', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recortar logo')),
                ('logo_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor=b'logo')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.EmpresaFabricante')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': 'precios',
            },
        ),
        migrations.CreateModel(
            name='PrecioActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo', to='precios.Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('busqueda', models.CharField(editable=False, max_length=250)),
                ('upc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='C\xf3digo de barras')),
                ('contenido', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('unidad_medida', models.CharField(blank=True, choices=[(b'gr', b'gr'), (b'kg', b'kg'), (b'ml', b'ml'), (b'l', b'l'), (b'unidad', b'unidad'), (b'm', b'm'), (b'm2', b'm2')], max_length=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('foto', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'productos')),
                ('oculto', models.BooleanField(default=False, help_text='Por ejemplo: productos discontinuados.S\xf3lo se encuentran por c\xf3digo de barra')),
                ('unidades_por_lote', models.IntegerField(blank=True, help_text='Cu\xe1ntas unidades vienen en un  pack mayorista. Por ejemplo 12  (latas de tomate).', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='precios.Categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.Marca')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text=b'Denominaci\xc3\xb3n com\xc3\xban. Ej: Jumbo de Alberdi', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('cp', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('horarios', models.TextField(blank=True, help_text=b'Ej: Horarios de atenci\xc3\xb3n', null=True, verbose_name=b'Notas')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('online', models.BooleanField(default=False, help_text=b'Es una sucursal online, no f\xc3\xadsica')),
                ('url', models.URLField(blank=True, null=True)),
                ('busqueda', models.CharField(editable=False, max_length=300)),
                ('cadena', models.ForeignKey(blank=True, help_text=b'Dejar en blanco si es un comercio \xc3\xbanico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='precios.Cadena')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
            },
        ),
        migrations.AddField(
            model_name='precioactivo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_activos', to='precios.Producto'),
        ),
        migrations.AddField(
            model_name='precioactivo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.Sucursal'),
        ),
        migrations.AddField(
            model_name='precio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='precios.Producto'),
        ),
        migrations.AddField(
            model_name='precio',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.Sucursal'),
        ),
        migrations.AddField(
            model_name='precio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descripcionalternativa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones', to='precios.Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='sucursal',
            unique_together=set([('direccion', 'ciudad')]),
        ),
        migrations.AlterUniqueTogether(
            name='precioactivo',
            unique_together=set([('producto', 'sucursal', 'precio')]),
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together=set([('nombre', 'fabricante')]),
        ),
    ]
