# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovilInfo',
            fields=[
                ('uuid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('phonegap', models.CharField(blank=True, max_length=100, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=200, null=True)),
                ('plataforma_version', models.CharField(blank=True, max_length=200, null=True)),
                ('preciosa_version', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movil_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
